# Generated by Django 4.2.6 on 2024-07-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stat',
            field=models.BooleanField(default=False),
        ),
    ]
