# Generated by Django 4.2.6 on 2024-07-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_student_days_student_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dayBin',
            field=models.IntegerField(default=0),
        ),
    ]
